### ISSUE TITLE
Calculation of the Generalized Advantage Estimation 

### ISSUE THREAD

**Issue by RobvanGastel** [MarcoMeter/recurrent-ppo-truncated-bptt#5]
Hi! Thanks for sharing the RNN-PPO implementation, it's very insightful. I have a question about the GAE calculation `calc_advantages` as part of the rollout buffer. 

My understanding is that the GAE is calculated over a single episode at a time. However, with the current approach the GAE is calculated over all the episodes combined per worker. If I am not mistaken about the implementation of the data sampling. 

The exact line I'm talking about:
https://github.com/MarcoMeter/recurrent-ppo-truncated-bptt/blob/9206a97b7546ec62e668eaf67ae6d4b752e0f0ee/trainer.py#L177

**Comment by MarcoMeter** [comment]
Hi @RobvanGastel 
thanks to reaching out!
It is more efficient to process the data by workers. To ensure that the GAE is computed episode-wise the mask from [line 181](https://github.com/MarcoMeter/recurrent-ppo-truncated-bptt/blob/9206a97b7546ec62e668eaf67ae6d4b752e0f0ee/buffer.py#L181) is used.

**Comment by RobvanGastel** [comment]
Thanks for pointing that out, I overlooked the boolean mask, sorry for the inconvenience. I have another question about the sampling of full episodes, does the zero padding affect the update method in any way, .e.g. have you observed any difference in using full episodes vs. padded ones?

https://github.com/MarcoMeter/recurrent-ppo-truncated-bptt/blob/9206a97b7546ec62e668eaf67ae6d4b752e0f0ee/buffer.py#L91

**Comment by MarcoMeter** [comment]
Padding is applied whenever a sequence is shorter than the expected sequence length. This also applies to full episodes. The padding is concatenated to the end of the sequence. During optimization, the padded values are masked. So in the end the padding is only useful for processing larger batches.

However, I'm not sure if the optimization is affected if the padding is concatenated before the beginning of the sequence.

**Comment by RobvanGastel** [comment]
Thanks for the quick response, it answered all my questions!

**Comment by MarcoMeter** [comment]
Happy to help!
