### ISSUE TITLE
Possibility to reference the implementation

### ISSUE THREAD

**Issue by RobvanGastel** [MarcoMeter/recurrent-ppo-truncated-bptt#6]
Hi, 

I used your implementation for my research project and would like to credit the work. Is it possible to add a BibTex to the readme.md?

**Comment by MarcoMeter** [comment]
Hi @RobvanGastel !

Great that this repository has value for your projects. When is your submission deadline? I've got a paper under review where this repository plays a major part. If there is enough time and my paper is accepted then it would be best to cite that paper. Otherwise I'll write a bib for citing this repository.

**Comment by RobvanGastel** [comment]
Thanks for the quick response! The submission deadline is 3rd of march, I hope this fits your timeline.

**Comment by MarcoMeter** [comment]
Well, just in case use this bibtex and if my paper is accepted, I'd appreciate it if you change the bibtex to the published paper in your camera-ready version. Rejection notifications will be sent on March 2nd, fingers crossed :D

```
@misc{Pleines2022,
  author = {Marco Pleines, Matthias Pallasch},
  title = {Recurrent Proximal Policy Optimization using Truncated BPTT},
  year = {2022},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/MarcoMeter/recurrent-ppo-truncated-bptt/}},
}
```

Just curious, what are you working on?

**Comment by RobvanGastel** [comment]
Thank you, I will change the citation once you receive the feedback. Goodluck on the publication! I hope it gets accepted.

I used the PPO implementation to combine it with RL^2 for neural architecture search.

**Comment by RobvanGastel** [comment]
I'm sad to hear that @MarcoMeter, the paper looks interesting! I will try to fit it into my paper as reference. Mine was rejected from the maintrack but invited to the autoML-Conf workshop track, so I might have to remove some details from my paper. 

Thank you for updating me!
