### ISSUE TITLE
Excuse me，how enjoy the model  “./models/cartpole_masked.nn”？ When I run enjoy.py ，  Show  "RuntimeError: expected scalar type Double but found Float "

### ISSUE THREAD

**Issue by jialuyu61** [MarcoMeter/recurrent-ppo-truncated-bptt#9]
Excuse me，how enjoy the model  “./models/cartpole_masked.nn”？ When I run enjoy.py ，  Show  "RuntimeError: expected scalar type Double but found Float
"

**Comment by MarcoMeter** [comment]
Hi @jialuyu61 
what version of PyTorch are you using? I can't reproduce your issue on my side.

**Comment by jialuyu61** [comment]
I am using pytorch 1.8.1 .

**Comment by MarcoMeter** [comment]
That's the same version that I tried to reproduce your issue as well. The problem seems to be that either the model parameters or its input (environment observation) are of type double and not float.

**Comment by MarcoMeter** [comment]
I close this issue as it seems stale. Please reach out again if you have further questions.
